console.log("Run Js External!");

//numbers
const age =18;
//String
const name = "AFSD";
//boolean
const bool = true;

const object = {};
const array = [];

//Let,var,const

//Let
let a =12;
a=30;
console.log(a);
//console.log(b);
//Var
var v ="run";
var v ="go";
console.log(v);
{var k = 12}
console.log(k);

//const
const o =12;
//o=30;
//const o=39;
{const y =98}
// console.log(y);

//Addition/(+)
const as = 12;
const n = 34;
const addition = as + n;
console.log(addition);



//Substraction(-)
const Substraction = n - as;
console.log(Substraction);

//Multiplication(*)
const Multiplication = as * n;
console.log(Multiplication);

//Division (/)
const division = n / as;
console.log(division);

//Modulus (%)
const division1 = n % as;
console.log(division);

//increment (++)
const division2 = n % as;
console.log(division);

//Deincrement
let j =10;
j--
console.log(j);

//comparison operators
const e =14;
const d =13;

//Equal(==)
console.log("Equal = ", e == d);

//Not Equal(!=)
console.log("Not Equal = ", e != d);

//Greater than(>)
console.log("Greater than = ", e > d);

//less than(>)
console.log("Less than = ", e < d);

//Greater than or Equal to(>=)
console.log("Greater than or Equal to = ", e >= d);

//Less than or Equal to(>=)
console.log("Less than or Equal to = ", e <= d);

//Logical Operators
const y = true;
const x = false;

//AND(&&)
console.log("AND = ",y && x);

//OR(||)
console.log("OR = ",y || x);

//NOT(!)
console.log("Not = ", !y);

//switch
const val = "AFSD";
switch (val) {
    case "Thushan":
        console.log('1');
        break;
    case "AFSD":
        console.log('2');
        break;
    default:
        console.log('error number');
}


